/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as MusicRouteImport } from './routes/music'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated/support.index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedSupportIdRouteImport } from './routes/_authenticated/support.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportIdRoute = AuthenticatedSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/design-system': typeof DesignSystemRoute
  '/dmca': typeof DmcaRoute
  '/help': typeof HelpRoute
  '/music': typeof MusicRoute
  '/podcasts': typeof PodcastsRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/design-system': typeof DesignSystemRoute
  '/dmca': typeof DmcaRoute
  '/help': typeof HelpRoute
  '/music': typeof MusicRoute
  '/podcasts': typeof PodcastsRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/design-system': typeof DesignSystemRoute
  '/dmca': typeof DmcaRoute
  '/help': typeof HelpRoute
  '/music': typeof MusicRoute
  '/podcasts': typeof PodcastsRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/support/$id': typeof AuthenticatedSupportIdRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/design-system'
    | '/dmca'
    | '/help'
    | '/music'
    | '/podcasts'
    | '/privacy'
    | '/radio'
    | '/settings'
    | '/sitemap.xml'
    | '/admin'
    | '/documents/$id'
    | '/support/$id'
    | '/documents/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/design-system'
    | '/dmca'
    | '/help'
    | '/music'
    | '/podcasts'
    | '/privacy'
    | '/radio'
    | '/settings'
    | '/sitemap.xml'
    | '/admin'
    | '/documents/$id'
    | '/support/$id'
    | '/documents'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/design-system'
    | '/dmca'
    | '/help'
    | '/music'
    | '/podcasts'
    | '/privacy'
    | '/radio'
    | '/settings'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/documents/$id'
    | '/_authenticated/support/$id'
    | '/_authenticated/documents/'
    | '/_authenticated/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DmcaRoute: typeof DmcaRoute
  HelpRoute: typeof HelpRoute
  MusicRoute: typeof MusicRoute
  PodcastsRoute: typeof PodcastsRoute
  PrivacyRoute: typeof PrivacyRoute
  RadioRoute: typeof RadioRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/$id': {
      id: '/_authenticated/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AuthenticatedSupportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedSupportIdRoute: typeof AuthenticatedSupportIdRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedSupportIdRoute: AuthenticatedSupportIdRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  DesignSystemRoute: DesignSystemRoute,
  DmcaRoute: DmcaRoute,
  HelpRoute: HelpRoute,
  MusicRoute: MusicRoute,
  PodcastsRoute: PodcastsRoute,
  PrivacyRoute: PrivacyRoute,
  RadioRoute: RadioRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
